export const ALL_BANNERS_REQUEST = "ALL_BANNERS_REQUEST";
export const ALL_BANNERS_SUCCESS = "ALL_BANNERS_SUCCESS";
export const ALL_BANNERS_FAIL = "ALL_BANNERS_FAIL";

export const ALL_ACTION_REQUSET = " ALL_ACTION_REQUSET";
export const ALL_ACTION_SUCCESS = " ALL_ACTION_SUCCESS";
export const ALL_ACTION_FAIL = " ALL_ACTION_FAIL";

export const ALL_COMEDY_REQUSET = " ALL_COMEDY_REQUSET";
export const ALL_COMEDY_SUCCESS = " ALL_COMEDY_SUCCESS";
export const ALL_COMEDY_FAIL = " ALL_COMEDY_FAIL";

export const ALL_THRILLER_REQUSET = "ALL_THRILLER_REQUSET";
export const ALL_THRILLER_SUCCESS = "ALL_THRILLER_SUCCESS";
export const ALL_THRILLER_FAIL = " ALL_THRILLER_FAIL";

export const ALL_ROMANTIC_REQUEST = "ALL_ROMANTIC_REQUEST";
export const ALL_ROMANTIC_SUCCESS = "ALL_ROMANTIC_SUCCESS";
export const ALL_ROMANTIC_FAIL = "ALL_ROMANTIC_FAIL";

export const GET_A_MOVIE_REQUEST = "GET_A_MOVIE_REQUEST";
export const GET_A_MOVIE_SUCCESS = "GET_A_MOVIE_SUCCESS";
export const GET_A_MOVIE_FAIL = "GET_A_MOVIE_FAIL";

export const SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_FAIL = "SEARCH_MOVIE_FAIL";
